- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - vars.yaml
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"