- name: variables from inventory
  hosts: web
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"