- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle unverified variables
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Kalyan') }}"

  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: "Fruits: {{ fruits | split(',') }}"

  - name: convert map to list
    vars:
      course:
        name: ansible 
        duration: 10 hrs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

