- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: execute ls command
  # ansible.builtin.command: ls -ltr > /tmp/outout.txt
    ansible.builtin.shell: ls -ltr > /tmp/outout.txt

  - name: execute ls command in command module
    #ansible.builtin.command: ls -ltr > /tmp/outout.txt
    #ansible.builtin.command: ls -ltr
    ansible.builtin.command: lssss -ltrrrfff
    register: command_result

  - name: print output
    ansible.builtin.debug:
     msg: "{{ command_result }}"